union SendMailResponse = SuccessResponse | FailureResponse

type SuccessResponse {
  message: String!
}

type FailureResponse {
  error: ErrorResponse
}

type ErrorResponse {
  message: String!
  code: String!
}
