type Mutation {
  createCategory(input: CategoryInput!): Category
  createBrand(input: BrandInput!): Brand
  updateCategory(id: ID!, input: CategoryInput!): Category
  updateBrand(id: ID!, input: BrandInput!): Brand
  deleteCategory(id: ID!): Category
  deleteBrand(id: ID!): Brand
}
