enum Order {
  asc
  desc
}

input Sort {
  field: String
  order: Order
}

input Filter {
  field: String
  value: String
}

type Query {
  categories(filter: Filter, limit: Int, offset: Int, sort: Sort): [Category!]!
  brands(filter: Filter, sort: Sort, limit: Int, offset: Int): [Brand!]!
  category(slug: String!): Category
  brand(slug: String!): Brand
}
